- name: Apt Update and clean on SBC
  hosts: sbceth
  tasks:
  - name: Run apt update and clean commands on remote services host
    #ansible.builtin.ping:
    ansible.builtin.shell: sudo apt update -y && sudo apt dist-upgrade -y ; sudo apt clean ; sudo apt autoclean ; sudo apt autoremove
    register: out

  - debug: var=out.stdout_lines
