- name: Update PVE Server
  hosts: pve
  tasks:
  - name: Run upgrade.sh script on PVE Server
    #ansible.builtin.ping:
    ansible.builtin.shell: cd ${HOME} && ./upgrade.sh
    register: out

  - debug: var=out.stdout_lines
