- name: Update all active pve services
  hosts: upgradepveactive
  tasks:
    - name: Run upgrade.sh script on remote services hosts
      #ansible.builtin.ping:
      ansible.builtin.shell: cd "${HOME}/dotfiles/common/ansible/clientscripts" && ./upgrade.sh
      register: out

    - debug: var=out.stdout_lines
