- name: Update all PVE services
  hosts: upgradepveall
  tasks:
  - name: Run upgrade.sh script on remote services hosts
    #ansible.builtin.ping:
    ansible.builtin.shell: cd ${HOME} && ./upgrade.sh
    register: out

  - debug: var=out.stdout_lines
